# this file defines behavior for the 'ganglia_master' class of nodes

- name: GANGLIA | Install HTTPD package
  yum: name=httpd state=installed
  only_if: "'$ansible_pkg_mgr' == 'yum'"

- name: GANGLIA | Install PHP
  yum: name=php state=installed

- name: GANGLIA | Ensure apache is running
  action: service name=httpd state=restarted

- name: GANGLIA | Install packages
  yum: name={{item}} state=installed
  with_items:
    - ganglia-gmetad
    - ganglia-gmond
    - hdp_mon_ganglia_addons
    - gweb
  notify:
     - restart httpd
  tags:
    - packages

- name: GANGLIA | Create RRDCached users
  user: name={{item}} state=present
  with_items:
        - nobody
        - rrdcached

- name: GANGLIA | create HDP objects directory
  file: path=/usr/libexec/hdp/ganglia state=directory

- name: GANGLIA | copy objects
  copy: src={{item}} dest=/usr/libexec/hdp/ganglia/ mode=755
  with_fileglob: ../files/ganglia_objects/* 

- name: GANGLIA | copy scripts
  copy: src={{item}} dest=/etc/init.d/ owner=root group=root mode=755
  with_fileglob: ../files/scripts/*

- name: GANGLIA | copy script
  template: src=../templates/{{item}}.j2 dest=/tmp/{{item}} mode=755
  with_items:
        - fix_bind_gmond.sh

- name: GANGLIA | Configure gmond
  command: sudo /usr/libexec/hdp/ganglia/setupGanglia.sh -c HDPJobTracker -m   

- name: GANGLIA | Configure gmond
  command: sudo /usr/libexec/hdp/ganglia/setupGanglia.sh -c HDPNameNode -m

- name: GANGLIA | Configure gmond
  command: sudo /usr/libexec/hdp/ganglia/setupGanglia.sh -c HDPSlaves -m

- name: GANGLIA | Configure gmond
  command: sudo /usr/libexec/hdp/ganglia/setupGanglia.sh -t

- name: GANGLIA | Make sure bind addresses are correct
  command: sh /tmp/fix_bind_gmond.sh

- name: GANGLIA | Make sure Ganglia is stopped
  service: name={{item}} state=stopped enabled=no
  with_items:
        - gmetad
        - gmond

- name: GANGLIA | Start Ganglia server
  command: sudo /etc/init.d/hdp-gmetad start
