---
- name: Start Zookeeper
  hosts: zookeeper
  sudo: Yes
  vars_files:
        - [ "vars/userGrp.yml" ]
        - [ "vars/dirsHDP.yml" ]
  tasks:
        - name: Zookeeper | Start Zookeeper
          command: sudo -u ${ZOOKEEPER_USER} /usr/lib/zookeeper/bin/zkServer.sh start ${ZOOKEEPER_CONF_DIR}/zoo.cfg

- name: Start HBase master
  hosts: hbaseMaster
  sudo: yes
  vars_files:
        - [ "vars/userGrp.yml" ]
        - [ "vars/dirsHDP.yml" ]
  tasks:
        - name: Start HBase master
          command: sudo -u ${HBASE_USER} ${HBASE_LIB_DIR}/bin/hbase-daemon.sh --config ${HBASE_CONF_DIR} start master

- name: Start HBase region servers
  hosts: hbaseRegionServers
  sudo: yes
  vars_files:
        - [ "vars/userGrp.yml" ]
        - [ "vars/dirsHDP.yml" ]
  tasks:
        - name: HBase | Start HBase Region servers
          command: sudo -u ${HBASE_USER} ${HBASE_LIB_DIR}/bin/hbase-daemon.sh --config ${HBASE_CONF_DIR} start regionserver

