---
- name: Stop HBase region servers
  hosts: hbaseRegionServers
  sudo: yes
  vars_files:
        - [ "vars/userGrp.yml" ]
        - [ "vars/dirsHDP.yml" ]
  tasks:
        - name: HBase | Stop HBase Region servers
          command: sudo -u ${HBASE_USER} ${HBASE_LIB_DIR}/bin/hbase-daemon.sh --config ${HBASE_CONF_DIR} stop regionserver

- name: Stop HBase master
  hosts: hbaseMaster
  sudo: yes
  vars_files:
        - [ "vars/userGrp.yml" ]
        - [ "vars/dirsHDP.yml" ]
  tasks:
        - name: Stop HBase master
          command: sudo -u ${HBASE_USER} ${HBASE_LIB_DIR}/bin/hbase-daemon.sh --config ${HBASE_CONF_DIR} stop master

- name: Stop Zookeeper
  hosts: zookeeper
  sudo: Yes
  vars_files:
        - [ "vars/userGrp.yml" ]
        - [ "vars/dirsHDP.yml" ]
  tasks:
        - name: Zookeeper | Stop Zookeeper
          command: sudo -u ${ZOOKEEPER_USER} /usr/lib/zookeeper/bin/zkServer.sh stop ${ZOOKEEPER_CONF_DIR}/zoo.cfg

