- hosts: hbaseMaster
  sudo: Yes
  vars_files:
        - [ "../vars/userGrp.yml" ]
        - [ "../vars/dirsHDP.yml" ]   
 
  tasks:
         
        - name: HBase | Install HBase
          yum: name={{item}} state=installed
          with_items:
                - hbase
        
        - name: HBase | Create HBase user
          user: name=${HBASE_USER} group=${HADOOP_GROUP} state=present

        - name: HBase | Delete HBase config directory
          file: path={item{}} state=absent
          with_items:
                - ${HBASE_CONF_DIR}

        - name: HBase | Delete default config
          file: path=${HBASE_CONF_DIR} state=absent

        - name: HBase | Create directories HBase
          file: path={{item}} state=directory owner=${HBASE_USER} group=${HADOOP_GROUP} mode=755 force=yes
          with_items:
                - ${HBASE_LOG_DIR}
                - ${HBASE_PID_DIR}
                - ${HBASE_CONF_DIR}

        - name: HBase | Copy new configuration files
          template: src=../templates/hbase/{{item}}.j2 dest=${HBASE_CONF_DIR}/{{item}} owner=${HBASE_USER} group=${HADOOP_GROUP} mode=755
          with_items:
                - hadoop-metrics.properties
                - hadoop-metrics.properties.master-GANGLIA
                - hadoop-metrics.properties.regionservers-GANGLIA
                - hbase-env.sh
                - hbase-policy.xml
                - hbase-site.xml
                - log4j.properties
                - regionservers

        - name: HBase | Set up HBase
          command: sudo -u ${HDFS_USER} hadoop fs -mkdir /apps/hbase
          ignore_errors: yes

        - name: HBase | Set up HBase
          command: sudo -u ${HDFS_USER} hadoop fs -chown -R ${HBASE_USER} /apps/hbase
          ignore_errors: yes

        - name: HBase | Start HBase
          command: sudo -u ${HBASE_USER} ${HBASE_LIB_DIR}/bin/hbase-daemon.sh --config ${HBASE_CONF_DIR} start master
