- hosts: hadoop_cluster
  sudo: Yes
  vars_files:
        - [ "../vars/userGrp.yml" ]
  
  tasks:
        - name: HDP | Configure Hortonworks yum repo 
          get_url: url=http://public-repo-1.hortonworks.com/HDP-1.2.0/repos/centos6/hdp.repo dest=/etc/yum.repos.d/hdp.repo force=no owner=root group=root

        - name: HDP | Create Hadoop group
          group: name=${HADOOP_GROUP} system=no

        - name: HDP | Create Hadoop users
          user: name={{ item }} group=${HADOOP_GROUP}
          with_items:
                - ${HDFS_USER}
                - ${MAPRED_USER}
        
