---
# Start MapReduce
# WARNING: NEED TO START HDFS first!

- hosts: hadoop_cluster
  sudo: Yes
  vars_files:
        - [ "../vars/userGrp.yml" ]
        - [ "../vars/nodeType.yml" ]
        - [ "../vars/dirsHDP.yml" ]
  
  tasks:
        - name: Create Mapreduce directory on HDFS -- JT
          command: sudo -u ${HDFS_USER} ${HADOOP_BIN}/hadoop fs -mkdir ${MAPREDUCE_HDFS_DIR}
          only_if: '$is_jobtracker'
          ignore_errors: yes

        - name: Change ownership Mapreduce directory on HDFS -- JT
          command: sudo -u ${HDFS_USER} ${HADOOP_BIN}/hadoop fs -chown -R ${MAPRED_USER} ${MAPREDUCE_HDFS_DIR}
          only_if: '$is_jobtracker'
          ignore_errors: yes
        

        - name: Start Mapreduce on jobtracker
          command: sudo -u ${MAPRED_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} start jobtracker
          only_if: '$is_jobtracker'

        - name: Start Mapreduce on tasktrackers
          command: sudo -u ${MAPRED_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} start tasktracker
          only_if: '$is_worker'

        - name: Start Mapreduce - history server
          command: sudo -u ${MAPRED_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} start historyserver
          only_if: '$is_history_server'

