# Start HDFS
- hosts: hadoop_cluster
  sudo: Yes
  vars_files:
        - [ "../vars/userGrp.yml" ]
        - [ "../vars/nodeType.yml" ]
        - [ "../vars/dirsHDP.yml" ]
  
  tasks:
        - name: Start HDFS on datanodes
          command: sudo -u ${HDFS_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} start datanode
          only_if: '$is_worker'

        - name: Start HDFS on namenode
          command: sudo -u ${HDFS_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} start namenode
          only_if: '$is_namenode'

        - name: Start HDFS on the secondarynamenode
          command: sudo -u ${HDFS_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} start secondarynamenode
          only_if: '$is_secondary_namenode'
