# Start HDFS
- hosts: hadoop_cluster
  sudo: Yes
  vars_files:
        - [ "../vars/userGrp.yml" ]
        - [ "../vars/nodeType.yml" ]
        - [ "../vars/dirsHDP.yml" ]
  
  tasks:
        - name: Stop HDFS on datanode
          command: sudo -u ${HDFS_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} stop datanode
          only_if: '$is_worker'

        - name: Stop HDFS on namenode
          command: sudo -u ${HDFS_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} stop namenode
          only_if: '$is_namenode'

        - name: Stop HDFS on the secondarynamenode
          command: sudo -u ${HDFS_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} stop secondarynamenode
          only_if: '$is_secondary_namenode'
