---
# Start MapReduce
# WARNING: NEED TO START HDFS first!

- hosts: hadoop_cluster
  sudo: Yes
  vars_files:
        - [ "../vars/userGrp.yml" ]
        - [ "../vars/nodeType.yml" ]
        - [ "../vars/dirsHDP.yml" ]
  
  tasks:
        - name: Stop Mapreduce on jobtracker
          command: sudo -u ${MAPRED_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} stop jobtracker
          only_if: '$is_jobtracker'

        - name: Stop Mapreduce on tasktrackers
          command: sudo -u ${MAPRED_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} stop tasktracker
          only_if: '$is_worker'

        - name: Stop Mapreduce on historyserver
          command: sudo -u ${MAPRED_USER} ${HADOOP_BIN}/hadoop-daemon.sh --config ${HADOOP_CONF_DIR} stop historyserver
          only_if: '$is_history_server'

