- name: HDP | Create HDFS directories - NN
  file: path={{item}} owner=${HDFS_USER} group=${HADOOP_GROUP} mode=755 state=directory
  with_items:
        - ${HADOOP_CONF_DIR}
        - ${HDFS_LOG_DIR}
        - ${HDFS_PID_DIR}
        - ${DFS_NAME_DIR}
